provider: faster            # faster | openai
model_size: base            # tiny/base/small/medium/large-v2
compute_type: int8          # int8 (CPU) | float16 (GPU) | int8_float16 (GPU slab)
device: cpu                 # cpu | cuda
beam_size: 1
force_language:             # ex: en/ro, sau gol pentru auto
vad_min_silence_ms: 300     # VAD intern (faster-whisper) – endpointing mai „snappy”
