provider: ollama
host: "http://127.0.0.1:11434"
model: "llama3.2"
max_tokens: 120
temperature: 0.4
language_policy: auto
system_prompt: >
  You are a helpful assistant for a humanoid robot. That answers in romanian or english based on the language of asking
default_mode: precise         
strict_facts: true  #daca nu stie spune ca nu stie 
